version: "3"
services:
  mysql:
    image: mysql:5
    container_name: snipe_mysql
    restart: always
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
  snipeit:
    image: snipe/snipe-it
    container_name: snipe-it
    restart: always
    depends_on:
      - mysql
    volumes:
      - ./config:/config
    environment:
      - PGID=1000
      - PUID=1000
    ports:
      - "8080:80"